[tox]
envlist = check, py312

[gh-actions]
python = 3.12: py312

[testenv]
usedevelop = true
passenv =
    DJANGO_SETTINGS_MODULE
    DJANGO_SECRET_KEY
    ADMIN_USERNAME
    ADMIN_PASSWORD
    ENTRY_FOLDER
deps =
    -r requirements.txt
    pytest
    pytest-django
commands =
    python -c "import Journal.settings; print('Settings OK')"
    python -c "import django; print('Django OK')"
    pytest --tb=short -x

[testenv:check]
ignore_errors = true
deps =
    flake8
    types-Pillow
    types-docutils
    types-setuptools
    pylint
commands =
    flake8 main
    flake8 tests
    pylint main

[flake8]
max-line-length = 180
per-file-ignores = __init__.py:F401
