# Generated by Django 4.1.3 on 2022-12-04 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=10)),
                ('content_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('name', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('first_created', models.DateTimeField()),
                ('last_edited', models.DateTimeField()),
                ('thumbnail_path', models.CharField(max_length=256)),
                ('content', models.ManyToManyField(to='main.content')),
            ],
        ),
        migrations.CreateModel(
            name='EntryParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=256)),
                ('original', models.BooleanField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entry')),
            ],
        ),
    ]
