# Generated by Django 4.1.3 on 2022-12-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryparagraph",
            name="height",
            field=models.IntegerField(default=220),
            preserve_default=False,
        ),
    ]
