# Generated by Django 4.1.3 on 2023-01-12 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_entryparagraph_height"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="thumbnail_path",
        ),
    ]
