# Generated by Django 5.2.13 on 2026-04-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_backfill_allow_ai_synthesis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entryparagraph",
            name="allow_ai_synthesis",
            field=models.BooleanField(),
        ),
    ]
