# Generated by Django 6.1 on 2026-09-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_entryparagraph_imported_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("mesh", "Mesh"),
                    ("paragraph", "Paragraph"),
                    ("video", "Video"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("right_x", models.FloatField(default=1.0)),
                ("right_y", models.FloatField(default=0.0)),
                ("right_z", models.FloatField(default=0.0)),
                ("up_x", models.FloatField(default=0.0)),
                ("up_y", models.FloatField(default=1.0)),
                ("up_z", models.FloatField(default=0.0)),
                ("forward_x", models.FloatField(default=0.0)),
                ("forward_y", models.FloatField(default=0.0)),
                ("forward_z", models.FloatField(default=-1.0)),
                ("radius", models.FloatField(default=3.0)),
                ("pan_x", models.FloatField(default=0.0)),
                ("pan_y", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="EntryMesh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=256)),
                ("image_path", models.CharField(max_length=256)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.entry"
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.camera",
                    ),
                ),
            ],
        ),
    ]
